# uv
export PATH="/home/niteris/.local/bin:$PATH"
. "$HOME/.cargo/env"
# >>> Photon CLI >>>
case ":$PATH:" in
  *:'/home/niteris/.photon/bin':*) ;;
  *) export PATH="$PATH":'/home/niteris/.photon/bin' ;;
esac
# <<< Photon CLI <<<
