#!/usr/bin/env bash
# Regenerates docs/hardware.md from the live machine. Called by capture.sh.
set -euo pipefail
# Deliberately no generation timestamp: it would change on every run, so
# this file would always show as modified and scripts/sync.sh could never
# report "nothing changed". git already records when it last moved.
cat <<HDR
# Hardware

Generated by \`scripts/gen-hardware-doc.sh\`, via scripts/capture.sh.
This is a record of the machine the config was captured from, for identifying
replacement parts and sanity-checking a restore. Nothing reads it at runtime.

## System

    hostname        $(hostname)
    NixOS           $(nixos-version)
    kernel          $(uname -r)
    CPU             $(lscpu | sed -n 's/^Model name: *//p') ($(nproc) threads)
    memory          $(free -h | awk '/^Mem:/{print $2}')

## Block devices

\`\`\`
$(lsblk -o NAME,SIZE,FSTYPE,LABEL,UUID,MOUNTPOINT)
\`\`\`

## Filesystems in use

$(sudo blkid | grep -E 'nvme|LABEL="root"' | sed 's/^/    /')

## Displays

$(python3 - <<'PY'
import json, pathlib
p = pathlib.Path.home()/".config/kwinoutputconfig.json"
try:
    for grp in json.loads(p.read_text()):
        for o in grp.get("data", []):
            if not isinstance(o, dict) or "connectorName" not in o: continue
            m = o.get("mode", {})
            print(f"    {o['connectorName']:<10} {o.get('edidIdentifier','?'):<24} "
                  f"{m.get('width')}x{m.get('height')}@{m.get('refreshRate',0)//1000}Hz  scale {o.get('scale')}")
except Exception as e:
    print(f"    (unavailable: {e})")
PY
)

## Audio capture devices

$(pactl list sources short 2>/dev/null | sed 's/^/    /' || echo "    (pipewire not reachable from this shell)")
HDR
