#!/usr/bin/env bash
# ── Captures live machine state, commits it, and pushes to GitHub ──
#
# The one command to run after changing anything on this machine that should
# survive a wipe. Run it from anywhere inside the repo:
#
#     scripts/sync.sh                      review the diff, then confirm
#     scripts/sync.sh -m "kitty: bigger font"
#     scripts/sync.sh -y                   no prompt, autogenerated message
#     scripts/sync.sh --dry-run            capture and show the diff only
#
# It refuses to push anything that looks like a credential -- see the scan
# below. This repo is private, but it deliberately holds no secrets, and that
# property is worth enforcing rather than remembering.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

MSG=""
ASSUME_YES=0
DRY_RUN=0
while [ $# -gt 0 ]; do
  case "$1" in
    -m|--message) MSG="${2:-}"; shift 2 ;;
    -y|--yes)     ASSUME_YES=1; shift ;;
    -n|--dry-run) DRY_RUN=1; shift ;;
    -h|--help)    sed -n '2,14p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

# ── 1. refuse to run on top of work that is not ours ──────────────────
# capture.sh overwrites tracked files wholesale. If the tree already has
# uncommitted edits, that would silently destroy them.
if [ -n "$(git status --porcelain)" ]; then
  echo "The working tree has uncommitted changes:"; echo
  git status --short
  cat <<'WARN'

capture.sh overwrites these files from the live machine, which would discard
whatever is above. Commit or stash first, then re-run.
WARN
  exit 1
fi

# ── 2. pull the machine's current state into the repo ─────────────────
echo "== capturing live state"
"$REPO/scripts/capture.sh" >/dev/null

if [ -z "$(git status --porcelain)" ]; then
  echo
  echo "Nothing changed -- the repo already matches this machine."
  exit 0
fi

# ── 3. credential scan, on the captured content ───────────────────────
# KDE and tool configs are captured verbatim, so a future settings file could
# start carrying a token without anyone noticing. Check before it is pushed,
# not after. Two passes (nixos#29):
#
#  - PATTERN below: fast, no dependency beyond grep, and it is what this
#    repo has actually been burned by. Kept as a cheap first line even
#    though gitleaks' default ruleset is a superset of it, because it needs
#    no network and no nix-store fetch to run.
#  - gitleaks (fetched via the pinned nixpkgs -- see the "nixpkgs#foo" trap
#    in CLAUDE.md for why that stays reproducible): entropy-aware, hundreds
#    of upstream-maintained detectors, config in .gitleaks.toml. It scans
#    the STAGED diff, which is why staging moves up to here instead of
#    step 5 -- `gitleaks protect --staged` needs something staged to look
#    at, and scanning the index rather than the working tree means it sees
#    exactly what capture.sh produced, gitignored build artifacts (result,
#    __pycache__) excluded for free. scripts/test-secrets-scan.sh proves
#    this pass actually catches something, rather than trusting a clean
#    run to mean the gate works and not just that it silently no-ops.
echo "== scanning for credentials (pattern)"
# Matches secret VALUES, not the words for them, so that the docs can discuss
# password hashes and this script can name its own patterns without tripping.
#   $y$ / $6$ / $2b$   crypt hashes with real payload after them
#   hashedPassword = " an actual Nix assignment, not a mention
PATTERN='gh[pousr]_[A-Za-z0-9]{30,}'
PATTERN="$PATTERN"'|github_pat_[A-Za-z0-9_]{20,}'
PATTERN="$PATTERN"'|sk-ant-[A-Za-z0-9_-]{20,}'
PATTERN="$PATTERN"'|AKIA[0-9A-Z]{16}'
PATTERN="$PATTERN"'|BEGIN [A-Z ]*PRIVATE KEY'
PATTERN="$PATTERN"'|xox[baprs]-[A-Za-z0-9-]{10,}'
PATTERN="$PATTERN"'|[$](y|6|2[aby])[$][./A-Za-z0-9]{8,}'
PATTERN="$PATTERN"'|hashedPassword[[:space:]]*=[[:space:]]*"'
PATTERN="$PATTERN"'|psk=.'

# This script is excluded from its own scan: it necessarily contains every
# pattern above, and a self-match would make the guard unusable.
scan_files() {
  git ls-files -com --exclude-standard | grep -vx 'scripts/sync.sh'
}

if scan_files | tr '\n' '\0' | xargs -0 -r grep -lIE "$PATTERN" 2>/dev/null | grep -q .; then
  echo >&2
  echo "REFUSING TO PUSH -- possible credentials in:" >&2
  scan_files | tr '\n' '\0' \
    | xargs -0 -r grep -nIE "$PATTERN" 2>/dev/null | sed 's/^/  /' >&2
  cat >&2 <<'WARN'

This repo is meant to hold no credentials. Remove the value, or add a narrow
exception to PATTERN in this script if it is a false positive.
WARN
  exit 1
fi

echo "== scanning for credentials (gitleaks)"
git add -A
if ! nix run nixpkgs#gitleaks -- protect --staged --redact --source "$REPO"; then
  echo >&2
  echo "REFUSING TO PUSH -- gitleaks found a possible credential above." >&2
  cat >&2 <<'WARN'

This repo is meant to hold no credentials. Remove the value, or -- only for a
confirmed false positive -- add a narrow [[allowlist]] entry to .gitleaks.toml.
WARN
  git reset >/dev/null
  exit 1
fi

# ── 4. show what changed ──────────────────────────────────────────────
echo
git status --short
echo
git --no-pager diff --cached --stat
echo

if [ "$DRY_RUN" = 1 ]; then
  git reset >/dev/null
  echo "dry run -- nothing committed. Inspect with: git diff"
  exit 0
fi

if [ -z "$MSG" ]; then
  # Name the top-level areas that moved, so an unattended sync still
  # produces a message worth reading in the log.
  AREAS="$(git status --porcelain | awk '{print $NF}' \
           | cut -d/ -f1 | sort -u | paste -sd', ' -)"
  MSG="sync: capture live state (${AREAS:-changes})"
fi

if [ "$ASSUME_YES" != 1 ]; then
  echo "Commit message: $MSG"
  read -rp "Commit and push to $(git remote get-url origin)? [y/N] " reply
  case "$reply" in
    [yY]*) ;;
    *) git reset >/dev/null; echo "aborted -- changes left in the tree"; exit 1 ;;
  esac
fi

# ── 5. commit and push ─────────────────────────────────────────────────
# Already staged by the gitleaks pass in step 3 -- no `git add -A` needed
# here, and re-running it would risk picking up something written to the
# tree in the gap between the scan and this point.
git commit -qm "$MSG"
git push -q origin HEAD
echo
echo "pushed: $(git log --oneline -1)"
